import '../styles/globals.css'
import 'tailwindcss/tailwind.css'
import Header from './components/Header/header'
import Footer from './components/footer/footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
  return (
    <>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </>
  )
}
