import '../styles/globals.css'
import 'tailwindcss/tailwind.css'
import Header from './components/Header/header'
import Footer from './components/footer/footer'
import { font } from '@/styles/font'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

function RootLayout ({ children }) {
  return (
    <>
      <body className={font.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </>
  )
}

export default RootLayout
